# Site settings
title:          RickTheCoder
description:    "A simple personal blog to share my knowledge while I am learning to code."
url:            https://github.com/Richardbmk/rickthecoder

# Author
author:
  name:         Ricardo Boriba Makuere
  email:        rdobmk@gmail.com
  url:          https://rickthecoder.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: rdobmk@gmail.com
  github: https://github.com/Richardbmk
  linkedin: https://www.linkedin.com/in/ricardoboriba/
